<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\mantle2\Service\ArticlesHelper;
use Drupal\mantle2\Service\PromptsHelper;

function mantle2_help($route_name, RouteMatchInterface $route_match)
{
	switch ($route_name) {
		case 'help.page.mantle2':
			$output = '';
			$output .= '<h3>' . \Drupal::translation()->translate('About') . '</h3>';
			$output .=
				'<p>' .
				\Drupal::translation()->translate('The Drupal backend for The Earth App') .
				'</p>';
			return $output;

		default:
	}
}

function mantle2_mail($key, &$message, $params)
{
	switch ($key) {
		case 'email_verification':
			$message['from'] = Drupal::config('system.site')->get('mail');
			$message['subject'] = Drupal::translation()->translate(
				'The Earth App - Email Verification Code',
			);
			$message['body'][] = Drupal::translation()->translate(
				'Your email verification code is: @code',
				[
					'@code' => $params['verification_code'],
				],
			);
			$message['body'][] = Drupal::translation()->translate(
				'This code will expire in 15 minutes.',
			);
			$message['body'][] = Drupal::translation()->translate(
				'If you did not request this verification, please ignore this email.',
			);
			break;
	}
}

function mantle2_cron()
{
	// Delete expired prompts and articles
	PromptsHelper::checkExpiredPrompts();
	ArticlesHelper::checkExpiredArticles();
	Drupal::logger('mantle2')->notice('[cron] mantle2 cron executed.');
}
